CREATE DATABASE keystone default CHARACTER SET UTF8;

CREATE TABLE users (
	idx INT PRIMARY KEY AUTO_INCREMENT,
	id VARCHAR(32) NOT NULL UNIQUE,
	pw VARCHAR(100) NOT NULL,
	email VARCHAR(32) NOT NULL,
	age INT NOT NULL,
	startTime INT,
	endTime INT
);
